
User: X6dftnlsjQAErCus

1UIXR816G6Vu7PAehn1uoJJeaFwWNoD5-rJkvLM-lq2M

Company: X6deMhQK7gAEFIDc

{
    "data": [
    {
    "id": "YHzGj9YWnAAE1ChB",
    "name": "1.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzIx2O6QwAE-J7F",
    "name": "10.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X6uHTPcJqgAEo4DJ",
    "name": "1:1",
    "project": {
    "id": "X6dfRp0lPwAEXT7X"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzG2hlg5wW0PYLb",
    "name": "2.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzGlNYWnAAE1ChD",
    "name": "3.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzGp9YWnAAE1Cjb",
    "name": "4.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzGn9YWnAAE1CjM",
    "name": "5.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzGmtYWnAAE1ChX",
    "name": "6.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X6uGhPcJqgAEo347",
    "name": "8.TEST2",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzIvWO6QwAE-J6r",
    "name": "9.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YDEzQ4GvBmicn0mb",
    "name": "Classes",
    "project": {
    "id": "YDEyiIGvBmX4n0mX"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_vrQf65tQAEfM7E",
    "name": "CSS",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X-zl3vxA1AAESFaU",
    "name": "Debugacion",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [
    {
    "id": "X7hS8G8awwAEgfy5",
    "weight": 0
    }
    ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YDQdtvyF0AAECwRB",
    "name": "Dismissal",
    "project": {
    "id": "YDQdrvyF0AAECwQu"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YR9PBbU6wgAEsKdj",
    "name": "Excel",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_vr9v65tQAEfNBX",
    "name": "Git",
    "project": {
    "id": "X_vr6f65tQAEfNBS"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_vrcf65tQAEfM7w",
    "name": "Google-Console",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_vrS_65tQAEfM7J",
    "name": "Javascript",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YB3EqKBvVgAEYNLf",
    "name": "Job away from computer",
    "project": {
    "id": "X7guHf5y_wAEhokB"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YNoKBmMQYgAEBGRP",
    "name": "LinkedIn",
    "project": {
    "id": "X_vr6f65tQAEfNBS"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X6dfRp0lPwAEXT7Z",
    "name": "Meeting",
    "project": {
    "id": "X6dfRp0lPwAEXT7X",
    "weight": 0
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X7guWP5y_wAEhooH",
    "name": "Meeting",
    "project": {
    "id": "X7guHf5y_wAEhokB"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X7harig8ngAEEOKq",
    "name": "MeetingNight",
    "project": {
    "id": "X7hagig8ngAEEOJR"
    },
    "status": "new",
    "reporterId": "X6dftnlsjQAErCus",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X6dfRp0lPwAEXT7a",
    "name": "Other work",
    "project": {
    "id": "X6dfRp0lPwAEXT7X",
    "weight": 0
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YDQdvfyF0AAECwRM",
    "name": "Payrolls",
    "project": {
    "id": "YDQdrvyF0AAECwQu"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YR9PCbU6wgAEsKdq",
    "name": "PowerBI",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YDEzSoGvBoYfn0mc",
    "name": "Reading",
    "project": {
    "id": "YDEyiIGvBmX4n0mX"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YJwByiDPeGkYGT7r",
    "name": "Recorridos",
    "project": {
    "id": "YJwBvSDPeG_oGT7p"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_vrUP65tQAEfM7M",
    "name": "Ruby",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_0XTX2FqQAEQXCN",
    "name": "T-Practice",
    "project": {
    "id": "X-zlDfxA1AAESFTW"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzG7ecHNwAE5UT_",
    "name": "T10.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzIOVukNtAtbbRI",
    "name": "T11.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YHzHCztOyQAEJyGb",
    "name": "T12.test",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X6uGefcJqgAEo34m",
    "name": "T13TEST1",
    "project": {
    "id": "X6uGa_cJqgAEo33w"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YJwB1CDPeCCqGT7s",
    "name": "Tarea relevante",
    "project": {
    "id": "YJwBvSDPeG_oGT7p"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YNS5rgzYoz1M5C2A",
    "name": "Task Manager 1",
    "project": {
    "id": "YNS5owzYo1e25C1_"
    },
    "status": "new",
    "reporterId": "X6dhV3lsjQAErCwy",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X6uGivcJqgAEo35E",
    "name": "TEST1",
    "project": {
    "id": "X6uGivcJqgAEo35D"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_38ODe1OgAE-pST",
    "name": "TEST1",
    "project": {
    "id": "X_38ODe1OgAE-pSS"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X6uGivcJqgAEo35F",
    "name": "TEST2",
    "project": {
    "id": "X6uGivcJqgAEo35D"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X_38ODe1OgAE-pSU",
    "name": "TEST2",
    "project": {
    "id": "X_38ODe1OgAE-pSS"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X7guTf5y_wAEhok5",
    "name": "Training",
    "project": {
    "id": "X7guHf5y_wAEhokB"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "X7hauyg8ngAEEOK_",
    "name": "TrainingNight",
    "project": {
    "id": "X7hagig8ngAEEOJR"
    },
    "status": "new",
    "reporterId": "X6dftnlsjQAErCus",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    },
    {
    "id": "YDEzYBgcCHY816w1",
    "name": "Vocabulary",
    "project": {
    "id": "YDEyiIGvBmX4n0mX"
    },
    "status": "new",
    "reporterId": "X6deMhQK7gAEFIDb",
    "deleted": false,
    "folders": [ ],
    "integration": {
    "provider": ""
    }
    }
    ],
    "paging": {
    "nItems": 43
    }
    }